apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: nodejs-bhwseqlp-gitops
  description: This is GitOps manifest for nodejs-bhwseqlp   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=nodejs-bhwseqlp
    backstage.io/kubernetes-id: nodejs-bhwseqlp 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-test-organization-jk/nodejs-bhwseqlp-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:nodejs-bhwseqlp
